FROM node:16.14.0-alpine3.15

RUN rm -rf /var/cache/apk/*

LABEL maintainer="firmanjs"

WORKDIR /usr/apps/socket-template-chat

ENV NODE_ENV development

COPY package.json /usr/apps/socket-template-chat/

RUN yarn install && yarn global add nodemon && yarn cache clean --all

CMD ["yarn", "dev"]
